services:
  frontend:
    container_name: react
    image: react:custom
    user: root
    build: ./frontend
    expose:
      - 5173
    ports:
      - 5173:5173
    volumes:
      - ./frontend/react_app:/app
    restart: on-failure
    networks:
      - febe
    depends_on:
      - backend
  
  backend:
    container_name: fastapi
    image: fastapi:custom
    user: root
    build: ./backend
    expose:
      - 8000
    ports:
      - 8000:8000
    volumes:
      - ./backend/fastapi_app:/app
    restart: on-failure
    networks:
      - bedb
      - febe
    depends_on:
      database:
        condition: service_healthy
    
  database:
    container_name: redis
    image: redis:custom
    user: root
    build: ./database
    expose:
      - 6379
    ports:
      - 6379:6379
    restart: on-failure
    networks:
      - bedb
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 3


networks:
  bedb:
    driver: bridge
  febe:
    driver: bridge
  