services:
  frontend:
    container_name: react
    image: react:custom
    user: root
    build: ./frontend
    env_file:
      - .env
    expose:
      - ${VITE_PORT}
    ports:
      - ${VITE_PORT}:${VITE_PORT}
    volumes:
      - ./frontend/react_app:/app
    restart: on-failure
    networks:
      - febe
    depends_on:
      - backend
  
  backend:
    container_name: fastapi
    image: fastapi:custom
    user: root
    build: ./backend
    env_file:
      - .env
    expose:
      - ${BE_PORT}
    ports:
      - ${BE_PORT}:${BE_PORT}
    volumes:
      - ./backend/fastapi_app:/app
    restart: on-failure
    networks:
      - bedb
      - febe
    depends_on:
      database:
        condition: service_healthy

  database:
    container_name: redis
    image: redis:custom
    user: root
    build: ./database
    env_file:
      - .env
    expose:
      - ${REDIS_PORT}
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    restart: on-failure
    networks:
      - bedb
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 3


networks:
  bedb:
    driver: bridge
  febe:
    driver: bridge
  