services:
  frontend:
    user: root
    build: ./frontend
    expose:
      - 5173
    ports:
      - 5173:5173
    volumes:
      - ./frontend/react_app:/app
    restart: on-failure
    networks:
      - default
    depends_on:
      - backend
  
  backend:
    user: root
    build: ./backend
    expose:
      - 8000
    ports:
      - 8000:8000
    volumes:
      - ./backend/fastapi_app:/app
    restart: on-failure
    networks:
      - default
    depends_on:
      database:
        condition: service_healthy
    
  database:
    user: root
    build: ./database
    expose:
      - 6379
    ports:
      - 6379:6379
    restart: on-failure
    networks:
      - default
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 3


networks:
  default:
    driver: bridge